[tool.poetry]
name = "xarray-selafin-backend"
version = "0.1.0"
description = ""
authors = ["tomsail <saillour.thomas@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9"
numpy = "*"
pytest = "*"
scipy = "*"
shapely = "*"
xarray = "*"
netcdf4 = "*"

[tool.poetry.group.dask.dependencies]
dask = "*"

[tool.poetry.plugins."xarray.backends"]
selafin = "xarray_selafin_backend.xarray_backend:SelafinBackendEntrypoint"


[tool.poetry.group.dev.dependencies]
matplotlib = "*"
netcdf4 = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
